const express = require('express');
const app = express();
const loginrouter = require('./loginroute');
const userroute = require('./userroute');
const sidemenuroute = require('./sidemenuroute');
const subsidemenuroute = require('./subsidemenuroute');
const serviceroute = require('./serviceroute');
const subserviceroute = require('./subserviceroute');
const uploadroute = require('./uploadroute.js');
const sliderroute = require('./sliderroute.js');
app.use('/api/user/',loginrouter);
app.use('/api/user/',userroute);
app.use('/api/sidemenu/',sidemenuroute);
app.use('/api/subsidemenu/',subsidemenuroute);
app.use('/api/service/',serviceroute);
app.use('/api/subservice/',subserviceroute);
app.use('/api/upload/',uploadroute);
app.use('/api/slider/',sliderroute);
module.exports = app;